GET http://localhost:8080/api/stock-register HTTP/1.1

###

POST http://localhost:8080/api/stock-register HTTP/1.1
content-type: application/json

{
    "symbol": "0123",
    "purchasePrice": "400",
    "quantity": "100",
    "targetPrice": "500",
    "cutlossPrice": "350"
}
