POST http://localhost:50000/api/stocks HTTP/1.1
content-type: application/json

{
    "symbol": "7203",
    "purchasePrice": "1000",
    "quantity": "100",
    "targetPrice": "1100",
    "stopLossPrice": "900",
    "status": "holding"
}

###

GET http://localhost:50000/api/stocks HTTP/1.1

###

PUT http://localhost:50000/api/stocks/1 HTTP/1.1
content-type: application/json

{
    "purchasePrice": "2000",
    "quantity": "200",
    "targetPrice": "2800",
    "stopLossPrice": "2600"
}